python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size base -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model bert -model_size large -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size base -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model spanbert -model_size large -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size base -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model xlnet -model_size large -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size base -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model roberta -model_size large -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size small -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size medium -pool_method coref
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method avg
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method max
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method diff
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method diff_sum
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method coherent
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method attn
python /home/shtoshni/Research/causality/tasks/copa/main.py -model gpt2 -model_size large -pool_method coref
